<div class="row justify-content-center">
  <div class="col-sm-6">
    <?php

    $title = 'Delete';
    $url   = $this->url('user', ['action' => 'delete', 'id' => $id]);

    $this->headTitle($title);
    ?>
    <h1> <?= $this->translate($title) ?> </h1>

    <p>
      <?= $this->translate('Are you sure that you want to delete user') ?> <b> <?= $this->escapeHtml($user->name) ?></b>?
    </p>

    <form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $user->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="<?= $this->translate('Yes') ?>" />
        <input type="submit" class="btn btn-success" name="del" value="<?= $this->translate('No') ?>" />
    </div>
    </form>
  </div>
</div>