<?php

$title = $user->name;
$this->headTitle($title);
?>
<h1> <?= $this->translate($title) ?> </h1>
<h2> <?= $this->translate('Departments') ?> </h2>

<button class="btn btn-success mb-2" data-toggle="modal" data-target="#createModal"> <?= $this->translate('Add to department') ?> </button>

<table class="table">
<tr>
    <th> <?= $this->translate('Title') ?> </th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($userDepartments as $department) : ?>
    <tr>
        <td><?= $this->translate($department['name']) ?></td>
        <td><a href="<?= $this->url('user-department', ['action' => 'delete', 'id' => $user->id], ['query' => [ 'department' => $department['id'] ]]); ?>" onclick="return confirm('<?= $this->translate('Are you sure?') ?>')"> <?= $this->translate('Exclude') ?> </a></td>
    </tr>
<?php endforeach; ?>
</table>

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createModalLabel"><?= $this->translate('Add') ?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="departmentForm" action="<?= $this->url('user-department', ['action' => 'create', 'id' => $user->id]); ?>" method="POST">
          <div class="form-group">
            <label> <?= $this->translate('Departments') ?> </label>
            <select multiple class="form-control" name="departments[]">
            <?php
              foreach($otherDepartments as $department) {
                echo "<option value='$department->id'> ".$this->translate($department->name)."</option>";
              }
            ?>
            </select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" form="departmentForm" class="btn btn-primary"><?= $this->translate('Add') ?></button>
      </div>
    </div>
  </div>
</div>